# this goes inside _config.yml. Change as required
navigation:
        - text: Home
          url: /index.html
        - text: Software
          url: /download.html
        - text: Publications
          url: /pubs.html
        - text: People
          url: /people.html

toolname: ASPIRE
